[project]
name = "sync-option"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Josh Brooks", email = "josh.vdbroek@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "canonicaljson>=2.0.0",
    "django-ninja>=1.4.1",
    "uuid-utils>=0.10.0",
    "uuid7>=0.1.0",
]

[project.scripts]
sync-option = "sync_option:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "django>=5.2",
    "django-debug-toolbar>=5.1.0",
    "django-extensions>=4.1",
    "factory-boy>=3.3.3",
    "ipython>=9.1.0",
    "jupyterlab>=4.4.0",
    "pytest-cov>=6.1.1",
    "pytest-django>=4.11.1",
]
playwright = [
    "playwright>=1.51.0",
]
server = [
    "gevent>=25.4.2",
    "gunicorn>=23.0.0",
]
