# Generated by Django 5.2 on 2025-04-18 09:25

import django.db.models.deletion
import uuid_utils._uuid_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, help_text='UUIDv7 for sync tracking')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('names', models.JSONField(default=dict)),
                ('descriptions', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, help_text='UUIDv7 for sync tracking')),
                ('value', models.CharField(max_length=255)),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer')], max_length=10)),
                ('names', models.JSONField(default=dict)),
                ('descriptions', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='sync_option.optiongroup')),
            ],
        ),
        migrations.CreateModel(
            name='OptionRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, help_text='UUIDv7 for sync tracking')),
                ('relation_type', models.CharField(max_length=50)),
                ('metadata', models.JSONField(default=dict)),
                ('from_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='sync_option.option')),
                ('to_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='sync_option.option')),
            ],
        ),
        migrations.AddConstraint(
            model_name='option',
            constraint=models.UniqueConstraint(fields=('group', 'value'), name='unique_option_value_per_group'),
        ),
        migrations.AddConstraint(
            model_name='optionrelation',
            constraint=models.UniqueConstraint(fields=('from_option', 'to_option', 'relation_type'), name='unique_option_relation'),
        ),
    ]
