# Generated by Django 5.2 on 2025-04-20 15:51

import sync_option.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_option', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='descriptions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='sync_id',
            field=models.UUIDField(default=sync_option.models.uuid7, editable=False, help_text='UUIDv7 for sync tracking'),
        ),
        migrations.AlterField(
            model_name='optiongroup',
            name='sync_id',
            field=models.UUIDField(default=sync_option.models.uuid7, editable=False, help_text='UUIDv7 for sync tracking'),
        ),
        migrations.AlterField(
            model_name='optionrelation',
            name='sync_id',
            field=models.UUIDField(default=sync_option.models.uuid7, editable=False, help_text='UUIDv7 for sync tracking'),
        ),
    ]
