# Generated by Django 5.2 on 2025-04-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_option', '0002_alter_option_descriptions_alter_option_sync_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionrelation',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
