# Generated by Django 5.2 on 2025-04-22 05:28

import django.db.models.deletion
import sync_option.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_option', '0003_alter_optionrelation_metadata'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='optionrelation',
            name='unique_option_relation',
        ),
        migrations.RemoveField(
            model_name='optionrelation',
            name='relation_type',
        ),
        migrations.CreateModel(
            name='GroupRelationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(default=sync_option.models.uuid7, editable=False, help_text='UUIDv7 for sync tracking')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('from_many', models.BooleanField(default=False, help_text='If True, multiple options from from_group can relate to the same to_group option')),
                ('to_many', models.BooleanField(default=False, help_text='If True, one from_group option can relate to multiple to_group options')),
                ('names', models.JSONField(default=dict)),
                ('descriptions', models.JSONField(blank=True, default=dict, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('from_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_types_from', to='sync_option.optiongroup')),
                ('to_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_types_to', to='sync_option.optiongroup')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('from_group', 'to_group', 'name'), name='unique_group_relation_type')],
            },
        ),
    ]
