# Generated by Django 5.2 on 2025-04-22 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_option', '0004_remove_optionrelation_relation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionrelation',
            name='relation_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='option_relations', to='sync_option.grouprelationtype'),
            preserve_default=False,
        ),
    ]
