# Generated by Django 5.2 on 2025-04-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_option', '0005_optionrelation_relation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouprelationtype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
